remove unnecessary cast
This fixes the following error on MSVC9:

debug.c(95) : error C2440: 'type cast' : cannot convert from 'GDebugKey' to 'GDebugKey'